### ISSUE TITLE
[Feat] 이미지 크롭 편집 기능 구현

### ISSUE THREAD

**Issue by Naknakk** [DeveloperAcademy-POSTECH/2024-MC2-M1-PrincessMaker#12]
## 🛠 Issue

수치사진 및 대표 사진을 등록하기 위한 이미지 크롭 편집 기능을 구현합니다.

## 📝 To-do

- [x] 이미지 크롭 편집 기능 구현
- [x] 비율 선택 기능 구현
- [x] 이미지 편집 뷰 디자인 적용
- [x] Modifier나 View로 간단하게 사용할 수 있도록 최종 구현
