### ISSUE TITLE
[Design] 정보 등록 화면 뷰 그리기

### ISSUE THREAD

**Issue by Cindy7878** [DeveloperAcademy-POSTECH/2024-MC2-M1-PrincessMaker#16]
## 🛠 Issue

- 제인이 만들어준 데이터를 바탕으로 정보등록화면 뷰를 그립니다 

## 📝 To-do

- [ ] (옷 카테고리 선택 뷰) 각 카테고리 선택 시 변수에 해당 값 저장
- [ ] (옷 이름 입력 뷰) 키보드 고정
- [x] (옷 이름 입력 뷰) text 입력되면 색 accentcolor로 바뀌게
- [x] (옷 이름 입력 뷰) 사용자가 입력한 이름 값 다음 뷰로 넘겨주기
- [ ] (옷 이름 입력 뷰) textfield 오른쪽 끝에 x 기호 추가
- [x] (사이즈 입력 뷰) 앞에서 입력받은 이름 값 띄워주기
- [x] (사이즈 입력 뷰) 창 넘어갈 때 자연스럽게 밑으로 내려가기..
- [ ] (옷 종류 선택 뷰) 해당 대분류에 맞는 소분류 화면에 띄우기
- [x] (옷 종류 선택 뷰) 선택된 것 하이라이트, 한개만 선택할 수 있게
- [x] 수치 사진 등록 뷰
- [x] 옷 사진 등록 뷰( optional)
- [x] 쇼핑을 시작합니다~ 뷰
