### ISSUE TITLE
[Design] Home UI 구현

### ISSUE THREAD

**Issue by Naknakk** [DeveloperAcademy-POSTECH/2024-MC2-M1-PrincessMaker#23]
## 🛠 Issue

Home UI 구현
## 📝 To-do

- [x] 상단 PIP 영역
- [x] 중간 카테고리 영역
- [x] 하단 옷 리스트 영역
