### ISSUE TITLE
[Feat] 정보 등록 뷰에 데이터 연결

### ISSUE THREAD

**Issue by darongzzang** [DeveloperAcademy-POSTECH/2024-MC2-M1-PrincessMaker#26]
## 🛠 Issue

디자인이 끝난 정보 등록 뷰를 CRUD가 가능한 상태로 만듭니다

## 📝 To-do

- [x] 메인 카테고리 뷰 완성
- [x] 이름 작성 뷰 완성
- [x] 사이즈 작성 뷰 완성
- [x] 서브 카테고리 뷰 완성
- [ ] 수치 사진 선택 뷰 완성
- [ ] 옷 사진 선택 뷰 완성
- [ ] 전체적으로 확인
