### ISSUE TITLE
[Feat] Pull to Refresh

### ISSUE THREAD

**Issue by Cindy7878** [DeveloperAcademy-POSTECH/2024-MC2-M1-PrincessMaker#28]
## 🛠 Issue

- 당기면 정보 등록 뷰로 넘어가는거 구현

## 📝 To-do

- [x] Pull to Refresh 적용해서 custom
- [ ] 로딩 아이콘을 + 아이콘으로 변경
- [ ] 뷰 넘어가는거 관련해서 수정..!?
