### ISSUE TITLE
[Feat] 정보 등록, 수정 뷰에 데이터 연결(브랜치 새로 팜)

### ISSUE THREAD

**Issue by darongzzang** [DeveloperAcademy-POSTECH/2024-MC2-M1-PrincessMaker#37]
## 🛠 Issue

디자인된 정보 등록 뷰, 정보 수정 뷰에 데이터를 연결해 작동 가능한 상태로 만듭니다

## 📝 To-do

- [x] 정보 등록 뷰 데이터 연결
- [ ] 정보 수정 뷰 데이터 연결
- [ ] 마지막 디자인 확인
