### ISSUE TITLE
[Chore] 앱 배포 준비를 위한 쇼케이스&UT 이후 피드백 반영

### ISSUE THREAD

**Issue by Naknakk** [DeveloperAcademy-POSTECH/2024-MC2-M1-PrincessMaker#50]
## 🛠 Issue

앱 배포 준비를 위해 쇼케이스&UT 이후 피드백을 반영합니다.

## 📝 To-do

- [x] 카테고리 순서 최신이 가장 왼쪽으로 오도록 변경하기
- [x] PIP 화면 4:5로 변경
- [x] 등록뷰 나오는 경우 PIP끄기
- [x] 옷 등록 안내 UX 라이팅 변경
- [x] 카테고리 탭 하여 이동 구현
