### ISSUE TITLE
[Docs] README 파일 수정

### ISSUE THREAD

**Issue by TakeMos** [DeveloperAcademy-POSTECH/2024-MC2-M1-PrincessMaker#55]
## 🛠 README 파일 수정

필요한 정보들을 넣을 예정입니다.
## 📝 To-do

- [x] 앱 로고 삽입
- [x] 스크린 샷 및 Gif 첨부
- [x] 팀원들이 맡은 파트 입력
- [x] 기술 스택 입력
