### ISSUE TITLE
[Feat] 로컬라이징

### ISSUE THREAD

**Issue by darongzzang** [DeveloperAcademy-POSTECH/2024-MC2-M1-PrincessMaker#67]
## 🛠 Issue

글로벌 출시를 위해 로컬라이제이션을 진행합니다

## 📝 To-do

- [ ] String 파일 생성
- [ ] 문자열 모두 번역 후 적용
- [ ] 등록-카테고리 선택 버튼 문자열 길이에 맞게 조정되도록 수정
