### ISSUE TITLE
[Feat] CRUD 기능 구현 및 데이터 모델 생성

### ISSUE THREAD

**Issue by darongzzang** [DeveloperAcademy-POSTECH/2024-MC2-M1-PrincessMaker#9]
## 🛠 Issue
SwiftData를 사용해서 저장할 데이터를 정의해두고, 뷰에서 CRUD가 가능하도록 합니다.

## 📝 To-do

- [x] @Model 짜서 연결하기
- [x] 데이터 뭐 필요한지 보고, 타입 정의하기
- [ ] 이미지 자체로 넘겨주도록 하기
- [x] 기본적인 CRUD 구현하기 (modelContext)
